name: asl-gokart/analytics
services:
  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3-core
    user: root
    ports:
      - ${INFLUX_PORT}:8181
    volumes:
      - ./influxdb3_data:/var/lib/influxdb3:z
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 8182:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - INFLUX_HOST=${INFLUX_HOST}
      - INFLUX_PORT=${INFLUX_PORT}
      - INFLUX_DATABASE=${INFLUX_DATABASE}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    depends_on:
      - influxdb3-core