apiVersion: 1

datasources:
  - name: InfluxDB_v3_SQL
    type: influxdb
    access: proxy
    url: http://influxdb3-core:${INFLUX_PORT}
    jsonData:
      version: SQL
      dbName: ${INFLUX_DATABASE}
      httpMode: POST
      insecureGrpc: true
    secureJsonData:
      token: ${INFLUX_TOKEN}