name: CI (headunit)
env:
    WORKING_DIRECTORY: 'infotainment/headunit'
'on':
    push:
        paths:
            - 'infotainment/headunit/**'
            - '!infotainment/headunit/**/*.md'
            - '!infotainment/headunit/LICENSE'
            - '!infotainment/headunit/**/*.gitignore'
    pull_request:
        paths:
            - 'infotainment/headunit/**'
            - '!infotainment/headunit/**/*.md'
            - '!infotainment/headunit/LICENSE'
            - '!infotainment/headunit/**/*.gitignore'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'npm'
                cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json
            - name: Install dependencies
              working-directory: ${{ env.WORKING_DIRECTORY }}
              run: npm install
            - name: Build (arm64)
              working-directory: ${{ env.WORKING_DIRECTORY }}
              run: npm run make:pi4
            - name: Upload artifact
              uses: actions/upload-artifact@v5
              with:
                name: headunit-deb-arm64
                path: ${{ env.WORKING_DIRECTORY }}/out/make/deb/arm64/*.deb
  